# "import" missing data
#Note: the binding is needed if testing on the workbench (or else it'll timeout) 
PREFIX ont: <http://localhost:8000/ontology#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

INSERT{
    ?S ?PLocal ?V
}
WHERE {
  BIND(<http://localhost:8000/resource/general-grievous> AS ?S) #only exists because I had to do case-by-case (else it reached timeout)
  ?S rdfs:seeAlso ?QID .
  ?PLocal ont:remoteEquivalent ?PRemote .
  SERVICE <https://query.wikidata.org/sparql> {
    ?QID ?PRemote ?VRemote .
    FILTER(LANG(?VRemote) = "en" || !isLiteral(?VRemote)) || LANG(?VRemote) = ""
  }
  OPTIONAL {
    ?VLocal rdfs:seeAlso ?VRemote .
    FILTER(isURI(?VRemote))
  }
  BIND(COALESCE(?VLocal, ?VRemote) AS ?V)
}


##Insert siblings
## Mudar wd:Q51746 para aceitar o url do character na pagina de detalhes

CONSTRUCT {
  ?localX :Sibling ?localY .
} WHERE {
  ?localX rdfs:seeAlso wd:Q51746 .
  ?localY rdfs:seeAlso ?y .

  SERVICE <https://query.wikidata.org/sparql> {
    {
      wd:Q51746 wdt:P22 ?parent .
      ?y wdt:P22 ?parent .
      FILTER(?y != wd:Q51746)
    }
    UNION
    {
      wd:Q51746 wdt:P25 ?parent .
      ?y wdt:P25 ?parent .
      FILTER(?y != wd:Q51746)
    }
  }
}


