# "import" missing data
#Note: the binding is needed if testing on the workbench (or else it'll timeout) 
PREFIX ont: <http://localhost:8000/ontology#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

INSERT{
    ?S ?PLocal ?V
}
WHERE {
  BIND(<http://localhost:8000/resource/general-grievous> AS ?S) #only exists because I had to do case-by-case (else it reached timeout)
  ?S rdfs:seeAlso ?QID .
  ?PLocal ont:remoteEquivalent ?PRemote .
  SERVICE <https://query.wikidata.org/sparql> {
    ?QID ?PRemote ?VRemote .
    FILTER(LANG(?VRemote) = "en" || !isLiteral(?VRemote)) || LANG(?VRemote) = ""
  }
  OPTIONAL {
    ?VLocal rdfs:seeAlso ?VRemote .
    FILTER(isURI(?VRemote))
  }
  BIND(COALESCE(?VLocal, ?VRemote) AS ?V)
}

# Siblings
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX : <http://localhost:8000/ontology#>

INSERT {
    ?localX :hasSibling ?target .
    ?target rdfs:label ?siblingLabel .
} WHERE {
    ?localX rdfs:seeAlso wd:{wikidata_id} .

    SERVICE <https://query.wikidata.org/sparql> {
        {
            wd:{wikidata_id} wdt:P22 ?parent .
            ?sibling wdt:P22 ?parent .
            FILTER(?sibling != wd:{wikidata_id})
        } UNION {{
            wd:{wikidata_id} wdt:P25 ?parent .
            ?sibling wdt:P25 ?parent .
            FILTER(?sibling != wd:{wikidata_id})
        }
        OPTIONAL { ?sibling rdfs:label ?siblingLabel FILTER (lang(?siblingLabel) = "en") }
    }

    BIND(COALESCE(?localY, ?sibling) AS ?target)

    OPTIONAL { ?localY rdfs:seeAlso ?sibling }

    FILTER NOT EXISTS { ?target rdfs:label ?siblingLabel }
    }
}

# Uncle

PREFIX : <http://localhost:8000/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>

INSERT {
    ?localX :hasUncle ?target .
    ?target rdfs:label ?uncleLabel .
} WHERE {
    ?localX rdfs:seeAlso wd:{wikidata_id} .

    SERVICE <https://query.wikidata.org/sparql> {
        wd:{wikidata_id} wdt:P22|wdt:P25 ?parent .
        ?uncle wdt:P22|wdt:P25 ?grandparent .
        ?parent wdt:P22|wdt:P25 ?grandparent .
        FILTER(?uncle != ?parent)
        ?uncle wdt:P21 wd:Q6581097 .
        OPTIONAL { ?uncle rdfs:label ?uncleLabel FILTER (lang(?uncleLabel) = "en") }
    }

    OPTIONAL { ?localUncle rdfs:seeAlso ?uncle }
    BIND(COALESCE(?localUncle, ?uncle) AS ?target)

    FILTER NOT EXISTS { ?target rdfs:label ?uncleLabel }
}

# Aunt
PREFIX : <http://localhost:8000/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>

INSERT {
    ?localX :hasAunt ?target .
    ?target rdfs:label ?auntLabel .
} WHERE {
    ?localX rdfs:seeAlso wd:{wikidata_id} .

    SERVICE <https://query.wikidata.org/sparql> {
        wd:{wikidata_id} wdt:P22|wdt:P25 ?parent .
        ?aunt wdt:P22|wdt:P25 ?grandparent .
        ?parent wdt:P22|wdt:P25 ?grandparent .
        FILTER(?aunt != ?parent)
        ?aunt wdt:P21 wd:Q6581072 .
        OPTIONAL { ?aunt rdfs:label ?auntLabel FILTER (lang(?auntLabel) = "en") }
    }

    OPTIONAL { ?localAunt rdfs:seeAlso ?aunt }
    BIND(COALESCE(?localAunt, ?aunt) AS ?target)

    FILTER NOT EXISTS { ?target rdfs:label ?auntLabel }
}

# Nephew
PREFIX : <http://localhost:8000/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>

INSERT {
    ?localX :hasNephew ?target .
    ?target rdfs:label ?nephewLabel .
} WHERE {
    ?localX rdfs:seeAlso wd:{wikidata_id} .

    SERVICE <https://query.wikidata.org/sparql> {
        wd:{wikidata_id} wdt:P22|wdt:P25 ?parent .
        ?sibling wdt:P22|wdt:P25 ?parent .
        FILTER(?sibling != wd:{wikidata_id})
        ?sibling wdt:P40 ?nephew .
        ?nephew wdt:P21 wd:Q6581097 .
        OPTIONAL { ?nephew rdfs:label ?nephewLabel FILTER (lang(?nephewLabel) = "en") }
    }

    OPTIONAL { ?localNephew rdfs:seeAlso ?nephew }
    BIND(COALESCE(?localNephew, ?nephew) AS ?target)
}
""",

# Niece
f"""
PREFIX : <http://localhost:8000/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>

INSERT {
    ?localX :hasNiece ?target .
    ?target rdfs:label ?nieceLabel .
} WHERE {
    ?localX rdfs:seeAlso wd:{wikidata_id} .

    SERVICE <https://query.wikidata.org/sparql> {
        wd:{wikidata_id} wdt:P22|wdt:P25 ?parent .
        ?sibling wdt:P22|wdt:P25 ?parent .
        FILTER(?sibling != wd:{wikidata_id})
        ?sibling wdt:P40 ?niece .
        ?niece wdt:P21 wd:Q6581072 .
        OPTIONAL { ?niece rdfs:label ?nieceLabel FILTER (lang(?nieceLabel) = "en") }
    }

    OPTIONAL { ?localNiece rdfs:seeAlso ?niece }
    BIND(COALESCE(?localNiece, ?niece) AS ?target)
}

# Grandfather

PREFIX : <http://localhost:8000/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>

INSERT {
    ?localX :hasGrandfather ?target .
    ?target rdfs:label ?grandfatherLabel .
} WHERE {
    ?localX rdfs:seeAlso wd:{wikidata_id} .

    SERVICE <https://query.wikidata.org/sparql> {
        wd:{wikidata_id} wdt:P22|wdt:P25 ?parent .
        ?parent wdt:P22 ?grandfather .
        OPTIONAL { ?grandfather rdfs:label ?grandfatherLabel FILTER (lang(?grandfatherLabel) = "en") }
    }

    OPTIONAL { ?localGrandfather rdfs:seeAlso ?grandfather }
    BIND(COALESCE(?localGrandfather, ?grandfather) AS ?target)
}

# Grandmother

PREFIX : <http://localhost:8000/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>

INSERT {
    ?localX :hasGrandmother ?target .
    ?target rdfs:label ?grandmotherLabel .
} WHERE {
    ?localX rdfs:seeAlso wd:{wikidata_id} .

    SERVICE <https://query.wikidata.org/sparql> {
        wd:{wikidata_id} wdt:P22|wdt:P25 ?parent .
        ?parent wdt:P25 ?grandmother .
        OPTIONAL { ?grandmother rdfs:label ?grandmotherLabel FILTER (lang(?grandmotherLabel) = "en") }
    }

    OPTIONAL { ?localGrandmother rdfs:seeAlso ?grandmother }
    BIND(COALESCE(?localGrandmother, ?grandmother) AS ?target)
}
""",

# Father in Law

PREFIX : <http://localhost:8000/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>

INSERT {
    ?localX :hasFatherInLaw ?target .
    ?target rdfs:label ?fatherInLawLabel .
} WHERE {
    ?localX rdfs:seeAlso wd:{wikidata_id} .

    SERVICE <https://query.wikidata.org/sparql> {
        wd:{wikidata_id} wdt:P26 ?spouse .
        ?spouse wdt:P22 ?fatherInLaw .
        OPTIONAL { ?fatherInLaw rdfs:label ?fatherInLawLabel FILTER (lang(?fatherInLawLabel) = "en") }
    }

    OPTIONAL { ?localFatherInLaw rdfs:seeAlso ?fatherInLaw }
    BIND(COALESCE(?localFatherInLaw, ?fatherInLaw) AS ?target)
}

#Mother in Law

PREFIX : <http://localhost:8000/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>

INSERT {
    ?localX :hasMotherInLaw ?target .
    ?target rdfs:label ?motherInLawLabel .
} WHERE {
    ?localX rdfs:seeAlso wd:{wikidata_id} .

    SERVICE <https://query.wikidata.org/sparql> {
        wd:{wikidata_id} wdt:P26 ?spouse .
        ?spouse wdt:P25 ?motherInLaw .
        OPTIONAL { ?motherInLaw rdfs:label ?motherInLawLabel FILTER (lang(?motherInLawLabel) = "en") }
    }

    OPTIONAL { ?localMotherInLaw rdfs:seeAlso ?motherInLaw }
    BIND(COALESCE(?localMotherInLaw, ?motherInLaw) AS ?target)
}

#Neto

PREFIX : <http://localhost:8000/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>

INSERT {
    ?localX :hasGrandson ?target .
    ?target rdfs:label ?grandchildLabel .
}
WHERE {
    ?localX rdfs:seeAlso wd:{wikidata_id} .

    SERVICE <https://query.wikidata.org/sparql> {
        wd:{federadaswikidata_id} wdt:P40 ?child .
        ?child wdt:P40 ?grandchild .
        ?grandchild wdt:P21 wd:Q6581097 .  # male
        OPTIONAL { ?grandchild rdfs:label ?grandchildLabel FILTER(LANG(?grandchildLabel) = "en") }
    }

    OPTIONAL { ?localGrandchild rdfs:seeAlso ?grandchild }
    BIND(COALESCE(?localGrandchild, ?grandchild) AS ?target)
}


#Neta

PREFIX : <http://localhost:8000/ontology#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX wd: <http://www.wikidata.org/entity/>

INSERT {
    ?localX :hasGranddaughter ?target .
    ?target rdfs:label ?grandchildLabel .
}
WHERE {
    ?localX rdfs:seeAlso wd:{wikidata_id} .

    SERVICE <https://query.wikidata.org/sparql> {
        wd:{wikidata_id} wdt:P40 ?child .
        ?child wdt:P40 ?grandchild .
        ?grandchild wdt:P21 wd:Q6581072 .  # female
        OPTIONAL { ?grandchild rdfs:label ?grandchildLabel FILTER(LANG(?grandchildLabel) = "en") }
    }

    OPTIONAL { ?localGrandchild rdfs:seeAlso ?grandchild }
    BIND(COALESCE(?localGrandchild, ?grandchild) AS ?target)
}

#UrbanCenter true

PREFIX : <http://localhost:8000/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT {
?city :UrbanCenter true .
}
WHERE {
?city a :City ;
        :population ?pop .
FILTER(xsd:integer(?pop) > 10000)
}

#Urban Center false

PREFIX : <http://localhost:8000/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

INSERT {
?city :UrbanCenter false .
}
WHERE {
?city a :City ;
        :population ?pop .
FILTER(xsd:integer(?pop) <= 10000)
}

#Planeta habitável false

PREFIX :     <http://localhost:8000/ontology#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

INSERT {
    ?planet :Habitable false .
}
WHERE {
    ?planet a :Planet .
    FILTER NOT EXISTS {
        ?planet :population ?pop .
        FILTER(str(?pop) != "")
    }
}

#Planeta Habitável true 

PREFIX :     <http://localhost:8000/ontology#>
PREFIX xsd:  <http://www.w3.org/2001/XMLSchema#>

INSERT {
    ?planet :Habitable true .
}
WHERE {
    ?planet a :Planet ;
            :population ?pop .
    FILTER(xsd:integer(?pop) > 0)
}

#Inferir Weapon 

PREFIX ont: <http://localhost:8000/ontology#>
INSERT {
    ?x a ont:Weapon .
}
WHERE {
    ?x ont:type ?type .
    FILTER(
        CONTAINS(LCASE(STR(?type)), "melee") ||
        CONTAINS(LCASE(STR(?type)), "blaster") ||
        CONTAINS(LCASE(STR(?type)), "explosive") ||
        CONTAINS(LCASE(STR(?type)), "projectile")
    )
}



