services:
  web:
    image: python:3.12-slim-bookworm
    container_name: web
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      graphdb:
        condition: service_healthy
    environment:
      - GRAPHDB_URL=http://graphdb:7200/repositories/starwars
    ports:
      - "8000:8000"
    command: bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"

  graphdb:
    image: ontotext/graphdb:10.8.4
    container_name: graphdb
    ports:
      - "7200:7200"
    environment:
      - GRAPHDB_URL=http://graphdb:7200/repositories/starwars
      - GRAPHDB_UPDATE_URL=http://graphdb:7200/repositories/starwars/statements
    healthcheck:
      test: ["CMD", "curl", "-f","-X","POST","-H","Content-Type: application/x-www-form-urlencoded","--data-urlencode","query=SELECT * WHERE { ?s ?p ?o } LIMIT 0", "http://localhost:7200/repositories/starwars"] #the first time, will only pass once we do the setup
      interval: 10s
      timeout: 5s
      retries: 100 #if the first-time initializing is not done by ~1500s, then please do so and then restart docker (if the first-time setup is done by then, the web container will start up by itself)
      #start_period: 30s
    volumes:
      - ./graphdb/data:/opt/graphdb/home
      - ./graphdb/import:/root/graphdb-import